version: '3'

dotenv:
    - .env

tasks:
    help:
        desc: print this help message
        cmds:
            - task --list-all
        silent: true

    build:
        desc: Build the API binary
        cmds:
            - go build -o ./tmp/main.exe ./cmd/api

    run:
        desc: run the cmd/api application with hot-reloading
        cmds:
            - air

    migrations:new:
        desc: create a new database migration
        vars:
            NAME: '{{.name | default ""}}'
        cmds:
            - |
                if [ -z "{{.NAME}}" ]; then
                  echo "Error: name parameter is required"
                  echo "Usage: task migrations:new name=migration_name"
                  exit 1
                fi
            - echo 'Creating migration file for {{.NAME}}...'
            - tern new -m ./internal/database/migrations {{.NAME}}

    migrations:up:
        desc: apply all up database migrations
        silent: true
        cmds:
            - 'tern migrate -m ./internal/database/migrations --host "{{index . "GO_AUTH_CRUD_DATABASE.HOST"}}" --port "{{index . "GO_AUTH_CRUD_DATABASE.PORT"}}" --user "{{index . "GO_AUTH_CRUD_DATABASE.USER"}}" --password "{{index . "GO_AUTH_CRUD_DATABASE.PASSWORD"}}" --database "{{index . "GO_AUTH_CRUD_DATABASE.NAME"}}" --sslmode "{{index . "GO_AUTH_CRUD_DATABASE.SSL_MODE"}}"'

    tidy:
        desc: format all .go files, and tidy and vendor module dependencies
        cmds:
            - echo 'Formatting .go files...'
            - go fmt ./...
            - echo 'Tidying module dependencies...'
            - go mod tidy
            - echo 'Verifying dependencies...'
            - go mod verify
